title: Herbert Komen
logo: /assets/img/Herbert.jpg
description: Highly motivated and detail-oriented Data Analyst with two years of experience in collecting, analyzing, and interpreting large datasets. Proficient in statistical analysis, data visualization, and data-driven decision-making. Seeking to leverage my analytical skills and technical expertise to drive business insights and optimize operational efficiencies.
show_downloads: true
theme: jekyll-theme-minimal
